hight = input('plz key in your hight: ')
weight = input('plz key in your weight: ')
name = input('plz key in your name: ')
print('Hi', name)
print('your hight is', hight, 'cm')
print('your weight is', weight, 'kg')
print('you are so beauty!')